// The database of fly species and their associated traits
const flyData = [
{
          id: 'l_cuprina_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'L. sericata complex', 'Lucilia cuprina'],
          distribution: ['HI', 'AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'MO', 'NC', 'OK', 'SC', 'TN', 'TX', 'DE', 'DC', 'IL', 'IN', 'IA', 'KY', 'MD', 'NE', 'PA', 'NJ', 'OH', 'SD', 'VA', 'WV', 'WI', 'AZ', 'CA', 'NV', 'NM', 'OR', 'WA'],
          species: 'Lucilia cuprina',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['about 20% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['bright silvery (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Occipitalsetae: ['stout and black'],
          Occipitalsetaebehindinnerverticalseta: ['a single seta.'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Bodycolor: ['coppery brown', 'reddish-orange brown', 'orangish green'],
          Setulaeonposteriorpostpronotum: ['small and number 2-3'],
          Setulaeonposteriornotopleuron: ['small and number 2-3'],
          acrostichalspostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['with apparent mesal division in which one half is microtomentose, the other half shining, often only visible when viewed from a sharp angle laterally  (Whitworth 2010)','without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_cuprina_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'L. sericata complex', 'Lucilia cuprina'],
          distribution: ['HI', 'AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'MO', 'NC', 'OK', 'SC', 'TN', 'TX', 'DE', 'DC', 'IL', 'IN', 'IA', 'KY', 'MD', 'NE', 'PA', 'NJ', 'OH', 'SD', 'VA', 'WV', 'WI', 'AZ', 'CA', 'NV', 'NM', 'OR', 'WA'],
          species: 'Lucilia cuprina',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)', 'Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['at least 35% of head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          IVSorientation: ['nearly parallel in dorsal view'],
          Parafacialwidthatleveloflunule: ['broader than the width of the first flagellomere'],
          Parafacialcolor: ['bright silvery (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Angleformedbyverticalsetae: ['a right angle'],
          Occipitalsetae: ['stout and black'],
          Occipitalsetaebehindinnerverticalseta: ['a single seta.'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Bodycolor: ['coppery brown', 'reddish-orange brown', 'orangish green'],
          Setulaeonposteriorpostpronotum: ['small and number 2-3'],
          Setulaeonposteriornotopleuron: ['small and number 2-3'],
          acrostichalspostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['with apparent mesal division in which one half is microtomentose, the other half shining, often only visible when viewed from a sharp angle laterally  (Whitworth 2010)','without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_magnicornis_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia magnicornis'],
          distribution: ['AK', 'AB', 'BC', 'NT', 'NU', 'SK', 'YT', 'MB', 'ON', 'QB', 'NL'],
          species: 'Lucilia magnicornis',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['about 13% head width', 'about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, more than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['three'],
          intraalarsetaepresutural: ['not present'],
          intraalarsetaePostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_magnicornis_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia magnicornis'],
          distribution: ['AK', 'AB', 'BC', 'NT', 'NU', 'SK', 'YT', 'MB', 'ON', 'QB', 'NL'],
          species: 'Lucilia magnicornis',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, more than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['three'],
          intraalarsetaepresutural: ['not present'],
          intraalarsetaePostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_cluvia_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia cluvia'],
          distribution: ['AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'MO', 'NC', 'OK', 'SC', 'TX'],
          species: 'Lucilia cluvia',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['about 8% head width', 'about 13% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['orange (Whitworth 2014)'],
          Genae: ['posterior third with many pale setae'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_cluvia_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia cluvia'],
          distribution: ['AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'MO', 'NC', 'OK', 'SC', 'TX'],
          species: 'Lucilia cluvia',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width', 'about 20% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['orange (Whitworth 2014)'],
          Genae: ['posterior third with many pale setae'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_sericata_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'L. sericata complex', 'Lucilia sericata'],
          distribution: ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'HI'],
          species: 'Lucilia sericata',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)', 'Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['about 13% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['bright silvery (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Occipitalsetae: ['stout and black'],
          Occipitalsetaebehindinnerverticalseta: ['two to five setae'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          Setulaeonposteriorpostpronotum: ['larger and number 6-8'],
          Setulaeonposteriornotopleuron: ['larger and number 6-8'],
          acrostichalspostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['with apparent mesal division in which one half is microtomentose, the other half shining, often only visible when viewed from a sharp angle laterally  (Whitworth 2010)','without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_sericata_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'L. sericata complex', 'Lucilia sericata'],
          distribution: ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'HI'],
          species: 'Lucilia sericata',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)', 'Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['at least 35% of head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          IVSorientation: ['convergent in dorsal view'],
          Parafacialwidthatleveloflunule: ['broader than the width of the first flagellomere'],
          Parafacialcolor: ['bright silvery (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Angleformedbyverticalsetae: ['an obtuse angle'],
          Occipitalsetae: ['stout and black'],
          Occipitalsetaebehindinnerverticalseta: ['two to five setae'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          Setulaeonposteriorpostpronotum: ['larger and number 6-8'],
          Setulaeonposteriornotopleuron: ['larger and number 6-8'],
          acrostichalspostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['with apparent mesal division in which one half is microtomentose, the other half shining, often only visible when viewed from a sharp angle laterally  (Whitworth 2010)','without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_silvarum_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'L. bufonivora complex', 'Lucilia silvarum'],
          distribution: ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'],
          species: 'Lucilia silvarum',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width', 'less than 7% of head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['about 8% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          presuturalacrostichalsetaeposteriorpairfirst: ['the posterior pair of presutural acrostichal setae are NOT much closer together to one another than they are to the posterior dorsocentral setae'],
          presuturalacrostichalsetaeposteriorpairsecond: ['the distance between the posterior pair of presutural acrostichal setae is NOT equal to the distance between them and the posterior-most presutural dorsocentral setae, but rather at least slightly less than that distance', 'the distance between the posterior pair of presutural acrostichal setae is equal to the distance between them and the posterior-most presutural dorsocentral setae, and not at least slightly less than that distance'],
          acrostichalspostsutural: ['two', 'three'],
          intraalarsetaepresutural: ['present'],
          intraalarsetaePostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Lowercalyptercolor: ['light brown, somewhat darker than upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['with 1-2 pairs of long, erect median marginal setae (Whitworth 2006)'],
          Malecercusinlateralview: ['with apical hook']
},
{
          id: 'l_silvarum_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'L. bufonivora complex', 'Lucilia silvarum'],
          distribution: ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'],
          species: 'Lucilia silvarum',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          presuturalacrostichalsetaeposteriorpairfirst: ['the posterior pair of presutural acrostichal setae are NOT much closer together to one another than they are to the posterior dorsocentral setae'],
          presuturalacrostichalsetaeposteriorpairsecond: ['the distance between the posterior pair of presutural acrostichal setae is NOT equal to the distance between them and the posterior-most presutural dorsocentral setae, but rather at least slightly less than that distance', 'the distance between the posterior pair of presutural acrostichal setae is equal to the distance between them and the posterior-most presutural dorsocentral setae, and not at least slightly less than that distance'],
          acrostichalspostsutural: ['two', 'three'],
          intraalarsetaepresutural: ['present'],
          intraalarsetaePostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['with 1-2 pairs of long, erect median marginal setae (Whitworth 2006)'],
          Femaleovipositorinventralview: ['with ST7 narrowing posteriorly, and ST8 elongate and parallel-sided']
},
{
          id: 'l_bufonivora_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'L. bufonivora complex', 'Lucilia bufonivora'],
          distribution: ['AK', 'AB', 'BC', 'NT', 'NU', 'SK', 'YT', 'ON', 'MB', 'WA', 'ID', 'MT', 'ND', 'MN', 'MI', 'NY'],
          species: 'Lucilia bufonivora',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['about 8% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          presuturalacrostichalsetaeposteriorpairfirst: ['the posterior pair of presutural acrostichal setae are NOT much closer together to one another than they are to the posterior dorsocentral setae', 'the posterior pair of presutural acrostichal setae are much closer together to one another than they are to the posterior dorsocentral setae'],
          presuturalacrostichalsetaeposteriorpairsecond: ['the distance between the posterior pair of presutural acrostichal setae is NOT equal to the distance between them and the posterior-most presutural dorsocentral setae, but rather at least slightly less than that distance'],
          acrostichalspostsutural: ['two', 'three'],
          intraalarsetaepresutural: ['present'],
          intraalarsetaePostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['with 1-2 pairs of long, erect median marginal setae (Whitworth 2006)'],
          Malecercusinlateralview: ['without apical hook'],
          Malesurstylus: ['bufonivora has distinct male terminalia. See Jones et al. (2019) or Tantawy+Whitworth (2014)'],
          Morphometricsbufonivoraelongata: ['bufonivora has distinct morphometrics of the antennae and frons that distinguish it from elongata. See Jones et al. 2019']
},
{
          id: 'l_bufonivora_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'L. bufonivora complex', 'Lucilia bufonivora'],
          distribution: ['AK', 'AB', 'BC', 'NT', 'NU', 'SK', 'YT', 'ON', 'MB', 'WA', 'ID', 'MT', 'ND', 'MN', 'MI', 'NY'],
          species: 'Lucilia bufonivora',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          presuturalacrostichalsetaeposteriorpairfirst: ['the posterior pair of presutural acrostichal setae are NOT much closer together to one another than they are to the posterior dorsocentral setae', 'the posterior pair of presutural acrostichal setae are much closer together to one another than they are to the posterior dorsocentral setae'],
          presuturalacrostichalsetaeposteriorpairsecond: ['the distance between the posterior pair of presutural acrostichal setae is NOT equal to the distance between them and the posterior-most presutural dorsocentral setae, but rather at least slightly less than that distance'],
          acrostichalspostsutural: ['two', 'three'],
          intraalarsetaepresutural: ['present'],
          intraalarsetaePostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['with 1-2 pairs of long, erect median marginal setae (Whitworth 2006)'],
          Femaleovipositorinventralview: ['with ST7 and ST8 gradually widened posteriorly']
},
{
          id: 'l_elongata_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'L. bufonivora complex', 'Lucilia elongata'],
          distribution: ['AB', 'BC', 'ID', 'MT', 'OR', 'WA', 'CA', 'NV'],
          species: 'Lucilia elongata',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['about 13% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          presuturalacrostichalsetaeposteriorpairfirst: ['the posterior pair of presutural acrostichal setae are NOT much closer together to one another than they are to the posterior dorsocentral setae', 'the posterior pair of presutural acrostichal setae are much closer together to one another than they are to the posterior dorsocentral setae'],
          presuturalacrostichalsetaeposteriorpairsecond: ['the distance between the posterior pair of presutural acrostichal setae is NOT equal to the distance between them and the posterior-most presutural dorsocentral setae, but rather at least slightly less than that distance'],
          acrostichalspostsutural: ['two', 'three'],
          intraalarsetaepresutural: ['present'],
          intraalarsetaePostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['with 1-2 pairs of long, erect median marginal setae (Whitworth 2006)'],
          Malecercusinlateralview: ['without apical hook'],
          Malesurstylus: ['elongata has distinct male terminalia. See Jones et al. (2019) or Tantawy+Whitworth (2014)'],
          Morphometricsbufonivoraelongata: ['elongata has distinct morphometrics of the antennae and frons that distinguish it from bufonivora. See Jones et al. 2019']
},
{
          id: 'l_elongata_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'L. bufonivora complex', 'Lucilia elongata'],
          distribution: ['AB', 'BC', 'ID', 'MT', 'OR', 'WA', 'CA', 'NV'],
          species: 'Lucilia elongata',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['at least partially dark brown to black'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          presuturalacrostichalsetaeposteriorpairfirst: ['the posterior pair of presutural acrostichal setae are NOT much closer together to one another than they are to the posterior dorsocentral setae', 'the posterior pair of presutural acrostichal setae are much closer together to one another than they are to the posterior dorsocentral setae'],
          presuturalacrostichalsetaeposteriorpairsecond: ['the distance between the posterior pair of presutural acrostichal setae is NOT equal to the distance between them and the posterior-most presutural dorsocentral setae, but rather at least slightly less than that distance'],
          acrostichalspostsutural: ['two', 'three'],
          intraalarsetaepresutural: ['present'],
          intraalarsetaePostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['with 1-2 pairs of long, erect median marginal setae (Whitworth 2006)'],
          Femaleovipositorinventralview: ['with ST7 and ST8 widened posteriorly after a sudden subapical constriction']
},
{
          id: 'l_thatuna_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia thatuna'],
          distribution: ['AZ', 'CA', 'CO', 'NV', 'NM', 'UT', 'ID', 'MT', 'OR', 'WA', 'WY', 'BC', 'AB'],
          species: 'Lucilia thatuna',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['less than 7% of head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['almost touching. See figures in Jones et al. 2019, p.167, 174, 180'],
          Fronswidthatnarrowestformales: ['about 5% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['with 1-2 pairs of long, erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_thatuna_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia thatuna'],
          distribution: ['AZ', 'CA', 'CO', 'NV', 'NM', 'UT', 'ID', 'MT', 'OR', 'WA', 'WY', 'BC', 'AB'],
          species: 'Lucilia thatuna',
          Headlength: ['Head longer; length of head at level of lunule more than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width', 'about 20% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialwidthatleveloflunule: ['narrower than the width of the first flagellomere'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['three'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_coeruleivirids_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia coeruleiviridis'],
          distribution: ['AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'MO', 'NC', 'OK', 'SC', 'TN', 'TX', 'MB', 'NB', 'NL', 'NS', 'ON', 'PE', 'QC', 'CT', 'DE', 'DC', 'IL', 'IN', 'IA', 'KY', 'ME', 'MD', 'MA', 'MI', 'MN', 'NE', 'NH', 'NJ', 'NY', 'ND', 'OH', 'PA', 'RI', 'SD', 'VT', 'VA', 'WV', 'WI', 'AZ', 'CA', 'CO', 'NV', 'NM', 'UT'],
          species: 'Lucilia coeruleiviridis',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['less than 7% of head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['almost touching. See figures in Jones et al. 2019, p.167, 174, 180'],
          Fronswidthatnarrowestformales: ['about 1% head width', 'about 3% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Genae: ['with dark setae only'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['light brown, somewhat darker than upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_coeruleivirids_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia coeruleiviridis'],
          distribution: ['AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'MO', 'NC', 'OK', 'SC', 'TN', 'TX', 'MB', 'NB', 'NL', 'NS', 'ON', 'PE', 'QC', 'CT', 'DE', 'DC', 'IL', 'IN', 'IA', 'KY', 'ME', 'MD', 'MA', 'MI', 'MN', 'NE', 'NH', 'NJ', 'NY', 'ND', 'OH', 'PA', 'RI', 'SD', 'VT', 'VA', 'WV', 'WI', 'AZ', 'CA', 'CO', 'NV', 'NM', 'UT'],
          species: 'Lucilia coeruleiviridis',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width', 'about 20% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Genae: ['with dark setae only'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['orange, yellow, or whitish'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_illustris_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia illustris'],
          distribution: ['AB', 'BC', 'NL', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'GA', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'ME', 'MD', 'MA', 'MI', 'MN', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'],
          species: 'Lucilia illustris',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['less than 7% of head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['somewhat separated. See figures in Jones et al. 2019, p.167'],
          Fronswidthatnarrowestformales: ['about 3% head width', 'about 5% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['1-5 black setae'],
          Basicostacolor: ['dark brown or black', 'tan to orange-brown'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_illustris_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia illustris'],
          distribution: ['AB', 'BC', 'NL', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'GA', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'ME', 'MD', 'MA', 'MI', 'MN', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'],
          species: 'Lucilia illustris',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width', 'about 20% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['large, with base extending more than halfway to lunule'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['reddish-orange brown', 'orangish green', 'yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['1-5 black setae'],
          Basicostacolor: ['dark brown or black', 'tan to orange-brown'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_mexicana_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia mexicana'],
          distribution: ['AZ', 'CA', 'NV', 'NM', 'UT', 'OK', 'TX', 'KS'],
          species: 'Lucilia mexicana',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['less than 7% of head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['somewhat separated. See figures in Jones et al. 2019, p.167'],
          Fronswidthatnarrowestformales: ['about 5% head width', 'about 8% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['dark silvery (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Genaldilation: ['greyish-white (with dark setae)'],
          Occipitalsetae: ['stout and black'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black', 'tan to orange-brown'],
          Lowercalyptercolor: ['light brown, somewhat darker than upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)'],
          Maleterminalia: ['posteriorly divergent; see Jones et al. 2019']
},
{
          id: 'l_mexicana_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia mexicana'],
          distribution: ['AZ', 'CA', 'NV', 'NM', 'UT', 'OK', 'TX', 'KS'],
          species: 'Lucilia mexicana',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width', 'about 20% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['dark silvery (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Genaldilation: ['greyish-white (with dark setae)'],
          Occipitalsetae: ['stout and black'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black', 'tan to orange-brown'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_eximia_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia eximia'],
          distribution: ['AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'OK', 'TX'],
          species: 'Lucilia eximia',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['conspicuously narrowed above antennal bases (and either the frons width is no more than about 15% of the head width at narrowest point, or this is male L cuprina or L magnicornis)'],
          FronswidthatnarrowesttohelpIDmales: ['less than 7% of head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['almost touching. See figures in Jones et al. 2019, p.167, 174, 180'],
          Fronswidthatnarrowestformales: ['about 3% head width', 'about 5% head width'],
          fronswidthvscuprinamale: ['at most about 15% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['orange (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Genaldilation: ['orangeish-white (with lighter brown setae)'],
          Occipitalsetae: ['pale and weak'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black', 'tan to orange-brown'],
          Lowercalyptercolor: ['light brown, somewhat darker than upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)'],
          Maleterminalia: ['posteriorly parallel; see Jones et al. 2019']
},
{
          id: 'l_eximia_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia eximia'],
          distribution: ['AL', 'AR', 'FL', 'GA', 'KS', 'LA', 'MS', 'OK', 'TX'],
          species: 'Lucilia eximia',
          Headlength: ['Head shorter; length of head at level of lunule less than half head height (Whitworth 2006)'],
          Fronsnarrowing: ['more or less parallel-sided; the frons width is significantly more than 20% of the head width at narrowest point'],
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Frontoorbitalplatesformaleswithnarrowfrons: ['strongly separated. See figures in Jones et al. 2019, p.174, 180'],
          Fronswidthatnarrowestformales: ['at least 30% head width', 'about 20% head width'],
          fronswidthvscuprinamale: ['at least about 20% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Parafacialcolor: ['orange (Whitworth 2014)'],
          Genae: ['with dark setae only'],
          Genaldilation: ['orangeish-white (with lighter brown setae)'],
          Occipitalsetae: ['pale and weak'],
          stflagellomerelengthrelativetoeyelength: ['in length, less than half of the height of eye in lateral view'],
          Palpscolor: ['entirely yellow-orange'],
          Bodycolor: ['yellowish green', 'emerald green', 'bluish'],
          acrostichalspostsutural: ['two'],
          Subcostalscleritesetae: ['no setae'],
          Basicostacolor: ['dark brown or black', 'tan to orange-brown'],
          Lowercalyptercolor: ['pale, similar to upper calypter'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence'],
          Tsetae: ['without especially strong or erect median marginal setae (Whitworth 2006)']
},
{
          id: 'l_graphita_male',
          m_or_f: 'male',
          taxonomy: ['Lucilia', 'Lucilia graphita'],
          distribution: ['HI'],
          species: 'Lucilia graphita',
          FronswidthatnarrowesttohelpIDmales: ['less than 7% of head width'],
          FronswidthatnarrowesttohelpIDfemales: ['less than 35% head width'],
          Ocellartriangle: ['relatively small, with basal swelling extending less than halfway to lunule'],
          Bodycolor: ['shining black'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence']
},
{
          id: 'l_graphita_female',
          m_or_f: 'female',
          taxonomy: ['Lucilia', 'Lucilia graphita'],
          distribution: ['HI'],
          species: 'Lucilia graphita',
          FronswidthatnarrowesttohelpIDmales: ['at least 7% of the head width'],
          Bodycolor: ['shining black'],
          Abdominalpubescence: ['without mesal division in abdominal pubescence']
}
];